export const BILLINGS_INFO = {
  "type": "object",
  "required": [
    "data"
  ],
  "properties": {
    "data": {
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "id",
          "pdf_url",
          "operator_id",
          "department_id",
          "member_id",
          "member_name",
          "partner_id",
          "partner_name",
          "office_id",
          "office_name",
          "office_detail",
          "title",
          "memo",
          "payment_condition",
          "billing_date",
          "due_date",
          "sales_date",
          "billing_number",
          "note",
          "document_name",
          "payment_status",
          "email_status",
          "posting_status",
          "created_at",
          "updated_at",
          "is_downloaded",
          "is_locked",
          "tag_names",
          "items",
          "excise_price",
          "excise_price_of_untaxable",
          "excise_price_of_non_taxable",
          "excise_price_of_tax_exemption",
          "excise_price_of_five_percent",
          "excise_price_of_eight_percent",
          "excise_price_of_eight_percent_as_reduced_tax_rate",
          "excise_price_of_ten_percent",
          "subtotal_price",
          "subtotal_of_untaxable_excise",
          "subtotal_of_non_taxable_excise",
          "subtotal_of_tax_exemption_excise",
          "subtotal_of_five_percent_excise",
          "subtotal_of_eight_percent_excise",
          "subtotal_of_eight_percent_as_reduced_tax_rate_excise",
          "subtotal_of_ten_percent_excise",
          "total_price"
        ],
        "properties": {
          "id": { "type": "string" },
          "pdf_url": { "type": "string" },
          "operator_id": { "type": "string" },
          "department_id": { "type": "string" },
          "member_id": { "type": "string" },
          "member_name": { "type": "string" },
          "partner_id": { "type": "string" },
          "partner_name": { "type": "string" },
          "office_name": { "type": "string" },
          "office_detail": { "type": "string" },
          "billing_date": { "type": "string" },
          "due_date": { "type": "string" },
          "created_at": { "type": "string" },
          "items": {
            "type": "array",
            "items": {
              "type": "object",
              "required": [
                "id",
                "name",
                "code",
                "detail",
                "unit",
                "price",
                "quantity",
                "excise",
                "created_at",
                "updated_at"
              ],
              "properties": {
                "id": { "type": "string" },
                "name": { "type": "string" },
                "code": { "type": "string" },
                "excise": { "type": "boolean" },
                "created_at": { "type": "string" },
                "updated_at": { "type": "string" }
              }
            }
          },
          "excise_price": { "type": "string" },
          "subtotal_price": { "type": "string" },
          "total_price": { "type": "string" }
        }
      }
    },
    "pagination": {
      "type": "object",
      "required": [
        "total_count",
        "total_pages",
        "per_page",
        "current_page"
      ],
      "properties": {
        "total_count": { "type": "number" },
        "total_pages": { "type": "number" },
        "per_page": { "type": "number" },
        "current_page": { "type": "number" }
      }
    }
  }
}

export const CREATE_BILLINGS = {
  "type": "object",
  "required": [
    "id",
    "pdf_url",
    "operator_id",
    "department_id",
    "member_id",
    "member_name",
    "partner_id",
    "partner_name",
    "office_id",
    "office_name",
    "office_detail",
    "title",
    "memo",
    "payment_condition",
    "billing_date",
    "due_date",
    "sales_date",
    "billing_number",
    "note",
    "document_name",
    "payment_status",
    "email_status",
    "posting_status",
    "created_at",
    "updated_at",
    "is_downloaded",
    "is_locked",
    "tag_names",
    "items",
    "excise_price",
    "excise_price_of_untaxable",
    "excise_price_of_non_taxable",
    "excise_price_of_tax_exemption",
    "excise_price_of_five_percent",
    "excise_price_of_eight_percent",
    "excise_price_of_eight_percent_as_reduced_tax_rate",
    "excise_price_of_ten_percent",
    "subtotal_price",
    "subtotal_of_untaxable_excise",
    "subtotal_of_non_taxable_excise",
    "subtotal_of_tax_exemption_excise",
    "subtotal_of_five_percent_excise",
    "subtotal_of_eight_percent_excise",
    "subtotal_of_eight_percent_as_reduced_tax_rate_excise",
    "subtotal_of_ten_percent_excise",
    "total_price"
  ],
  "properties": {
    "id": { "type": "string" },
    "operator_id": { "type": "string" },
    "department_id": { "type": "string" },
    "member_id": { "type": "string" },
    "member_name": { "type": "string" },
    "partner_id": { "type": "string" },
    "partner_name": { "type": "string" },
    "office_name": { "type": "string" },
    "office_detail": { "type": "string" },
    "title": { "type": "string" },
    "billing_date": { "type": "string" },
    "due_date": { "type": "string" },
    "created_at": { "type": "string" },
    "items": { "type": "array" },
    "excise_price": { "type": "string" },
    "subtotal_price": { "type": "string" },
    "total_price": { "type": "string" }
  }
}